# -*- coding: utf-8 -*-
# Generated by Django 2.1 on 2018-09-24 02:04
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_token")]

    operations = [
        migrations.AddField(
            model_name="token",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="token",
            name="uid",
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
