# -*- coding: utf-8 -*-
# Generated by Django 2.1 on 2018-09-24 02:05
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_auto_20180923_1904")]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        )
    ]
