# -*- coding: utf-8 -*-
# Generated by Django 2.1 on 2018-09-24 01:42
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("lists", "0004_item_list")]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ("id",)}),
        migrations.AlterField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="lists.List",
            ),
        ),
        migrations.AlterUniqueTogether(name="item", unique_together={("list", "text")}),
    ]
