# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-15 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lists", "0004_item_list")]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ("id",)}),
        migrations.AlterUniqueTogether(
            name="item", unique_together=set([("list", "text")])
        ),
    ]
